# language: php
build:
  nodes:
    analysis:
      environment:
        php: 7.4
      dependencies:
        after:
          - git clone --depth=1 https://github.com/XOOPS/XoopsCore25
          - git clone --depth=1 https://github.com/mambax7/tag
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

    php74:
      environment:
        php: 7.4
      tests:
        override:
          - command: phpunit

    php80:
      environment:
        php: 8.0
      tests:
        override:
          - command: phpunit

    php81:
      environment:
        php: 8.1
      tests:
        override:
          - command: phpunit

    php82:
      environment:
        php: 8.2
      tests:
        override:
          - command: phpunit

    php83:
      environment:
        php: 8.3
      tests:
        override:
          - command: phpunit

    php84:
      environment:
        php: 8.4
      tests:
        override:
          - command: phpunit

filter:
  excluded_paths:
    - 'tests/*'
  dependency_paths:
    - XoopsCore25/*
    - tag/*
